### ISSUE TITLE
Links to codesandbox are broken

### ISSUE THREAD

**Issue by notnotgabriel** [magnetis/astro#118]
# Description

Links to codesandbox direct me to an error page
`413. That’s an error.`
![image](https://user-images.githubusercontent.com/5247142/59442837-5f6a6400-8dd1-11e9-8a89-70685cdfa6b7.png)

# Expected behavior

Open codesandbox.io containing the component I selected.

# Steps to reproduce

Click in any codesandbox.io link.
![Screen Shot 2019-06-13 at 11 52 35](https://user-images.githubusercontent.com/5247142/59443131-d869bb80-8dd1-11e9-8ee3-3bfc73d6f2f0.png)

**Comment by victorheringer** [comment]
As stated [here](https://github.com/magnetis/astro/pull/182), this is an docz problem and this functionally will be disabled by now!
